Paises/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail'),
    url(r'^(?P<pk>[0-9]+)/resultados/$', views.Resultados.as_view(), name = 'resultados'),
    url(r'^(?P<id_pais>[0-9]+)/ciudades/$',views.ciudades, name = 'ciudades'),
]

l4paises/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^Paises/' , include('Paises.urls', namespace = "Paises")),
    url(r'^admin/', include(admin.site.urls)),
]

Paises/models.py
from django.db import models

# Create your models here.

class Pais(models.Model):
    Codigo = models.CharField(max_length = 3)
    Nombre = models.CharField(max_length = 70)
    Continente = models.CharField(max_length = 65)
    Region = models.CharField(max_length = 70)
    Area = models.DecimalField(max_digits = 30, decimal_places = 2)
    Independence = models.IntegerField(default = 1500)

    def __str__(self):
        return self.Nombre


class Ciudad(models.Model):
    Ciudad_pais = models.ForeignKey(Pais)
    Nombre_Ciudad = models. CharField(max_length = 70)
    Distrito = models.CharField(max_length = 60)
    Poblacion = models.IntegerField(default = 0)

    def __str__(self):
        return self.Nombre_Ciudad


class Lenguaje(models.Model):
    Lenguaje_Pais = models.ForeignKey(Pais)
    Lenguaje = models.CharField(max_length = 70)

    def __str__(self):
        return self.Lenguaje

Paises/views.py
from django.shortcuts import get_object_or_404, render
from .models import Pais, Ciudad
from django.views import generic
# Create your views here.

class IndexView(generic.ListView):
    model = Pais
    template_name = 'Paises/index.html'
    context_object_name = 'Agregado_Reciente'

    def get_queryset(self):
        return Pais.objects.all()

class DetailView(generic.DetailView):
    model = Pais
    template_name = 'Paises/detail.html'


class Resultados(generic.DetailView):
    model = Pais
    template_name = 'Paises/resultados.html'

def ciudades(request, id_pais):
    p = get_object_or_404(Pais, pk = id_pais)
    try:
        ciudad_seleccionada = p.ciudad_set.get(pk = request.POST['ciudad'])
    except (KeyError, Ciudad.DoesNotExist):
        return render(request, 'Paises/detail.html', {
            'pais': p,
            'error_message': "No has hecho ninguna seleccion.",
        })
    else:
        ciudad_seleccionada.save()
        return render(request,'Paises/resultados.html', {'pais':p})

Paises/templates/Paises/detail.html
<!DOCTYPE html>
<html>
	<head>
	<link rel="stylesheet" type="text/css" href="http://tito.neuronageek.com/css/bootstrap.min.css" media="all" />
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h1>{{pais.Nombre}}</h1>
					{% if error_message %}<p><strong class="bg-danger">{{ error_message }}</strong></p>{% endif %}

					<form action = "{% url 'Paises:ciudades' pais.id %}" method = "post">
						{% csrf_token %}
						{% for ciudad in pais.ciudad_set.all %}
							<div class="form-control">

								<label for="ciudad{{forloop.counter}}" class="checkbox-inline"><input type = "radio" name = "ciudad" id = "ciudad{{forloop.counter}}" value="{{ciudad.id}}" />{{ciudad.Nombre_Ciudad}}</label>
							</div>
							{% endfor %}
						<input type = "submit" value = "Chequear Ciudad" />
					</form>
				</div>
			</div>
		</div>
	</body>
</html>

Paises/templates/Paises/index.html
<!DOCTYPE html>
<html>
	<head>
	<link rel="stylesheet" type="text/css" href="http://tito.neuronageek.com/css/bootstrap.min.css" media="all" />
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h1>Paises del mundo</h1>

					{% if Agregado_Reciente %}
						<ul class="col-md-12 list-group">
						{% for pais in Agregado_Reciente %}
							<li class="list-group-item"><a href = "{% url 'Paises:detail' pais.id %}">{{pais.Nombre}}</a></li>
						{% endfor %}
						</ul>
					{% else %}
						<p class="bg-danger">No hay paises.</p>
					{% endif %}
					<h1>{{ pais.Nombre }}</h1>
				</div>
			</div>
		</div>
	</body>
</html>

Paises/templates/Paises/resultados.html
<!DOCTYPE html>
<html>
	<head>
	<link rel="stylesheet" type="text/css" href="http://tito.neuronageek.com/css/bootstrap.min.css" media="all" />
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h1>{{ pais.Nombre }}</h1>

					<ul class="list-group">
					{% for idioma in pais.lenguaje_set.all %}
					<li class="list-group-item">Lenguaje: {{idioma.Lenguaje}}</li>
					{% endfor %}
					{% for ciudad in pais.ciudad_set.all %}
						<li class="list-group-item">{{ciudad.Nombre_Ciudad}} -- Distrito: {{ciudad.Distrito}} -- Poblacion: {{ciudad.Poblacion}}</li>
					{% endfor %}
					</ul>

					<a href="{% url 'Paises:detail' pais.id %}" class="btn btn-primary"> Mostrar Pais Otra Vez?</a>
				</div>
			</div>
		</div>
	</body>
</html>